services:
  dev-db:
    image: postgres
    env_file: .env
    ports:
      - '5432:5432'
    restart: unless-stopped
  dev-redis:
    image: redis
    ports:
      - '6380:6379'
    restart: unless-stopped
  # dev-app:
  #   image: backendapi:latest
  #   env_file: .env
  #   volumes:
  #     - ./images:/home/node/images
  #   ports:
  #     - '3000:3000'
