services:
  dev-db:
    image: postgres
    env_file: .env
    ports:
      - '5432:5432'
    restart: unless-stopped
  test-db:
    image: postgres
    env_file: .env.test
    ports:
      - '5433:5432'
    restart: unless-stopped
