name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        id: docker_build
        with:
          push: true
          tags: ghcr.io/sebasptsch/nestjsblogapi:latest
      - name: Install Dive
        run: |
          wget https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.deb
          sudo apt install ./dive_0.9.2_linux_amd64.deb
      - name: Run Dive
        run: |
          CI=true dive ghcr.io/sebasptsch/nestjsblogapi:${{ steps.docker_build.outputs.imageid }} >> $GITHUB_STEP_SUMMARY

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} >> $GITHUB_STEP_SUMMARY
